### ISSUE TITLE
Add-On is no longer available in Chrome Web Store

### ISSUE THREAD

**Issue by simonai1254** [eddex/hslu-simple-mep-results#102]
**Describe the bug**
The add-on is no longer available in Chrome Web Store. 

**Expected behavior**
The [Link](https://chrome.google.com/webstore/detail/hslu-simple-mep-results/bkcgbpgefenaapagldnnabfakilmfihp) in the Readme File points to the Add-On in the Chrome Web Store.

**Actual behavior**
A 404 Error appears and the add-on can not be found in the chrome web store by searching for it.

**Steps to Reproduce**
1. Open https://chrome.google.com/webstore/detail/hslu-simple-mep-results/bkcgbpgefenaapagldnnabfakilmfihp

**Contributing (please choose one)**
- [ ] I'd like to help implementing this feature!
- [ ] I don't have the time to work on this.
- [X] This is out of scope for me (CONTRIBUTING.md)

**Comment by eddex** [comment]
duplicate #98
