### ISSUE TITLE
Undefined Modules: ENGDB, MAREP & PRG

### ISSUE THREAD

**Issue by Elmeche** [eddex/hslu-simple-mep-results#13]
Good Day,

Thanks for this addon, it's very usefull.

I have found the following undefined Modules in my subscription:

ENGDB
Typ: Zusatzmodul

MAREP
Typ: Repetitorium

Best Regards
Marco

**Comment by eddex** [comment]
Hi Marco

Thanks for your comment. I am not aware of any modules with type 'Repetitorium'. Can you elaborate on that?

**Comment by Elmeche** [comment]
Repetitorium are the Courses/Modules, you can do as a preparation for the bachelor study. MAREP is for example the Mathematics Repetitorium.
They aren't really part of the Bachelor Course but are still listed under Subscriptions (Anmeldung). I think it looks a little nasty, if they are marked as undefined (As you can see below).

![Addon](https://user-images.githubusercontent.com/49430274/64412296-5f57c880-d08f-11e9-9df8-a8303de84cb1.png)
![HSLU](https://user-images.githubusercontent.com/49430274/64412303-654da980-d08f-11e9-9dbc-16268af382c4.png)

**Comment by eddex** [comment]
ENGDB is listed as 'Erweiterungsmodul' for 'Wirtschaftsinformatik'.

We should parse the data from https://mycampus.hslu.ch/de-ch/info-i/dokumente-fuers-studium/bachelor/einschreibung/modulbeschriebe/modulbeschriebe-wirtschaftsinformatik-neues-curriculum/ and add it to `data/modules_wi.json`

**Comment by Lextum** [comment]
> 
> 
> ENGDB is listed as 'Erweiterungsmodul' for 'Wirtschaftsinformatik'.
> 
> We should parse the data from https://mycampus.hslu.ch/de-ch/info-i/dokumente-fuers-studium/bachelor/einschreibung/modulbeschriebe/modulbeschriebe-wirtschaftsinformatik-neues-curriculum/ and add it to `src/data/modules_wi.json`

Should be solved with release #35

**Comment by janedoekills** [comment]
Hi, PRG is listed as undefined for ICS, perhaps also for others though. It's a Kernmodul. Thanks!
<img width="445" alt="Screenshot 2020-02-07 at 10 40 58" src="https://user-images.githubusercontent.com/39761062/74018520-59477a00-4996-11ea-8790-b435c312efce.png">

**Comment by eddex** [comment]
fixed in release [2.0.13](https://github.com/eddex/hslu-simple-mep-results/releases/tag/2.0.13)

The update will be installed automatically.

If you can't wait, you can go to _about:addons_ in Firefox and press "Check for updates".
![image](https://user-images.githubusercontent.com/5302085/74051409-2e7e1580-49d8-11ea-9659-7b21d992acf1.png)
