### ISSUE TITLE
Overview does not work with new styling

### ISSUE THREAD

**Issue by florianbaer** [eddex/hslu-simple-mep-results#14]
When i open the pages containing "Meine Anmeldungen", this addon is unable to read the "Noten" and the "Bewertungen".

**Comment by eddex** [comment]
Hi @florianbaer 

Thanks for reporting this issue! 

Seems like they did a breaking change in the API. The new JSON response for modules looks like this:
![image](https://user-images.githubusercontent.com/5302085/68025361-d33bd900-fcac-11e9-9dd4-0e6170c55eb8.png)
