### ISSUE TITLE
Filter or define I.INFO_BSCI module on the overview

### ISSUE THREAD

**Issue by nerrehmit** [eddex/hslu-simple-mep-results#15]
Looks like they started listing the "Infoveranstaltung" by Mr. Diethelm similar to your courses with the status "angemeldet".

I think it would make sense to filter this "module" or as an alternative simply include it in the module list that it doesn't show as undefined. 
I also suspect there are more similar modules for WI, Security and Digital Ideation perhaps? 

Let me know if you want me to include them in the module list.

![I INFO_BSCI](https://user-images.githubusercontent.com/15264624/70848578-f2b14e80-1e73-11ea-8426-4d17d4e3d8d5.png)

![BSCI-expanded](https://user-images.githubusercontent.com/15264624/70848579-f6dd6c00-1e73-11ea-9997-95285d1c993c.png)

**Comment by eddex** [comment]
Thanks for reporting this issue! We could add it to the 'other modules' section in the [parse_module_type.py](https://github.com/eddex/hslu-simple-mep-results/blob/7db34fe64fa66514946d19a427454a3ea99af2da/tools/parse_module_type.py#L76) script. But what would be the module-type of this?

Regarding other WI, ICS or DI modules: Currently they are not fully supported yet. See #9 for more info.

**Comment by eddex** [comment]
I.INFO_BSCI and I.INT_EINFTA are now shown with module type `-`

![image](https://user-images.githubusercontent.com/5302085/72843304-87d90b80-3c9a-11ea-8799-6ec57bf2a2a3.png)
