### ISSUE TITLE
BA_GEST is not recognized as Zusatzmodul

### ISSUE THREAD

**Issue by TheHuebschi** [eddex/hslu-simple-mep-results#50]
**What do you study?**
- [X] Informatik
- [ ] Security
- [ ] Wirtschaftsinformatik
- [ ] Digital Ideation

**Which modules are not recognized by the add-on? And what type should they have?**
- BA_GEST (Zusatzmodul)

**Screenshots**
![grafik](https://user-images.githubusercontent.com/33907022/74733992-dce25000-524d-11ea-9f62-efcc95efa467.png)

**More info**
-

**Comment by eddex** [comment]
Thanks for reporting this issue!

The problem is in the `module_parser` due to a conflict with other special cases where the module name contains an underscore:

https://github.com/eddex/hslu-simple-mep-results/blob/16363e06a5e9aa029151c790ecc2423e00935e0e/src/components/module_parser.js#L101
