### ISSUE TITLE
Business IT modules missing and inconsistencies

### ISSUE THREAD

**Issue by christofkaelin** [eddex/hslu-simple-mep-results#69]
**What do you study?**
- [ ] Informatik
- [ ] Security
- [x] Wirtschaftsinformatik
- [ ] Digital Ideation

**Which modules are not recognized by the add-on? And what type should they have?**
- IPEUS → Projektmodul
- PIPE → Projektmodul
- STA1 → Kernmodul in Wirtschaftsinformatik/ICS, otherwise Erweiterungsmodul
- GPOR → Kernmodul in Wirtschaftsinformatik, otherwise Erweiterungsmodul
- WEBT → Kernmodul in Wirtschaftsinformatik/ICS (#48), otherwise Erweiterungsmodul
- MWI1 → Kernmodul
- MAT1 → Kernmodul
- MWI2 → Kernmodul
- TUNE → Zusatzmodul
- STO → Zusatzmodul
- FV → Zusatzmodul

**Screenshots**
<img width="1245" alt="WI_Modules" src="https://user-images.githubusercontent.com/23083479/83046752-b9e2eb80-a047-11ea-9b9e-20616936a78f.png">

**More info**
STA1, GPOR and WEBT all have a `_K` after their abbreviation. Possible way to differentiate them from their Erweiterungsmodul-Counterpart (?)
Same goes for ISF, which seems to be a Kernmodul for Informatik, Wirtschaftsinformatik, ICS but an Erweiterungsmodul for the new AI course (see https://mycampus.hslu.ch/-/media/campus/common/files/dokumente/other/mycampus/i/dokumente-ausbildung/bachelor/modulbeschriebe-ics/information-security-fundamentals.pdf?la=de-ch)

**Comment by Lextum** [comment]
IPEUS, PIPE, TUNE, STO, FV those aren't on the official [HSLU page.](https://mycampus.hslu.ch/de-ch/info-i/dokumente-fuers-studium/bachelor/einschreibung/modulbeschriebe/) right?

Are you sure, you don't get credits for the TUTH1901? We parse the information from your MyCampus page and normally if a module has credits you should get them.

At the moment we only support I, WI and ICS. I will look into the AI course, shouldn't be to hard to add those modules.

**Comment by christofkaelin** [comment]
IPEUS and PIPE form together the [International Project Experience](https://www.hslu.ch/en/lucerne-school-of-information-technology/degree-programs/bachelor/wirtschaftsinformatik/einblick-ins-studium/) in the Silicon Valley. You can find it [here](https://mycampus.hslu.ch/-/media/campus/common/files/dokumente/other/mycampus/i/dokumente-ausbildung/bachelor/modulbeschriebe-wi-und-iim-neues-curriculum/international-project-experience.pdf) on MyCampus.
[TUNE](https://www.isa-campus.ch/de-ch/angebote/tourismus-und-nachhaltige-entwicklung/), [STO](https://www.isa-campus.ch/de-ch/angebote/studienreise-nach-osteuropa-st-petersburg/) and [FV](https://www.isa-campus.ch/en/angebote/filmfestival-in-bukarest/) are all ISA modules.

Regarding MAT1_TUT: AFAIK, the tutors receive credits for tutoring students. But as a participant I surely don't. On MyCampus it says "Ohne Modulabschluss" – maybe the tutors have a different status here?
<img width="586" alt="MAT1" src="https://user-images.githubusercontent.com/23083479/83078223-638ea080-a079-11ea-80ee-69d416aa3000.PNG">

**Comment by eddex** [comment]
Should be fixed with #70. But we need to create a new release.

**Comment by Lextum** [comment]
> Regarding MAT1_TUT: AFAIK, the tutors receive credits for tutoring students. But as a participant I surely don't. On MyCampus it says "Ohne Modulabschluss" – maybe the tutors have a different status here?

Could you check, if the credits are added to your total credits? When i'm not mistaken, they shouldn't.

**Comment by christofkaelin** [comment]
> Could you check, if the credits are added to your total credits? When i'm not mistaken, they shouldn't.

That's right, they are not added to my total credits.

Suggestion: to make it less confusing, could you ~~strikethrough~~ the modules in the list which don't count towards the total?

**Comment by Lextum** [comment]
> 
> 
> > Could you check, if the credits are added to your total credits? When i'm not mistaken, they shouldn't.
> 
> That's right, they are not added to my total credits.
> 
> Suggestion: to make it less confusing, could you ~strikethrough~ the modules in the list which don't count towards the total?

I will look into it. Maybe we can do same CSS magic and give the users a better overview, which module counts and which isn't.

**Comment by Lextum** [comment]
I added strikethrough based on passed value. I'm not 100% sure if it covers every HSLU module status.
Modules with 'successfully participated' is passed, module with 'attested' or 'enrolled' are unknown. Everything else will be striked out
![image](https://user-images.githubusercontent.com/5988613/83729975-b99aaf80-a648-11ea-960e-15a9c02be80f.png)

If you wanna help, you could test the chances. Just clone the repo, switch to the branch **enhancement/markFailedModules** and follow the source installation instructions in the  **README.md**.

**Comment by christofkaelin** [comment]
Sure! To me it looks like this:
<img width="557" alt="hslu-mycampus" src="https://user-images.githubusercontent.com/23083479/83794368-3441ea00-a69e-11ea-97a4-4bbe919c7cf5.PNG">

Regarding the status of the ones that are striked through:
MAREP is _Teilgenommen erfüllt_
MAT1_TUT is _Ohne Modulabschluss_
IPEUS is _Bestätigt_
The others which are not striked through are either _Erfolgreich teilgenommen_ or _Testat erfüllt_

**Comment by Lextum** [comment]
I wonder, do IPEUS and MAREP count against the credit total at the moment? Either my new commits have a logic flaw or we found another "bug" in the extension.
