### ISSUE TITLE
Credits zaehlen auch wenn keine Bewertung eingetragen

### ISSUE THREAD

**Issue by timofurrer** [eddex/hslu-simple-mep-results#7]
Kann es sein, dass Credits nicht in der Uebersicht gezaehlt werden, wenn fuer dieses Modul keine Bewertung existiert?

**Comment by eddex** [comment]
Ja, Module welche nicht bestanden wurden (F, FX) oder keine Bewertung haben werden nicht mitgezählt.

**Comment by timofurrer** [comment]
> Oder hast du ein Beispiel, bei welchem ein Modul ohne Bewertung gezählt werden sollte?

Ja, zum Beispiel individuelle Anrechnungen:

![image](https://user-images.githubusercontent.com/1008252/61723184-f5e45a80-ad6b-11e9-961f-98ad46a96629.png)

RCC:

![image](https://user-images.githubusercontent.com/1008252/61723238-10b6cf00-ad6c-11e9-9e3b-158afd90752d.png)

Irgendwie habe ich auch zwei PTA - aber keine Ahnung wieso ..

**Comment by eddex** [comment]
> Ja, zum Beispiel individuelle Anrechnungen

Diese "Modul" scheint meiner Meinung nach noch nicht abgeschlossen zu sein. Bei mir steht ebenfalls 0 ECTS, vielleicht tut sich da ja noch was. Sollte aber für die Berechnung keinen Einfluss haben, da 0 ECTS.

> RCC

Bei RCC sollte nach erfolgreichem Abschluss eine Bewertung vorhanden und somit die ECTS mit in die berechnung einbezogen sein.
![image](https://user-images.githubusercontent.com/5302085/61727787-3b0c8a80-ad74-11e9-879f-5f33ace3791e.png)

> Irgendwie habe ich auch zwei PTA - aber keine Ahnung wieso ..

Ist bei mir auch so, wird aber nur 1 Mal gezählt da nur eines davon bewertet ist.

**Comment by timofurrer** [comment]
> Diese "Modul" scheint meiner Meinung nach noch nicht abgeschlossen zu sein. Bei mir steht ebenfalls 0 ECTS, vielleicht tut sich da ja noch was. Sollte aber für die Berechnung keinen Einfluss haben, da 0 ECTS.

Okay, mal schauen :)

> Bei RCC sollte nach erfolgreichem Abschluss eine Bewertung vorhanden und somit die ECTS mit in die berechnung einbezogen sein.

Bei mir ist das Modul selbst als "Erfolgreich teilgenommen" eingetragen:

![image](https://user-images.githubusercontent.com/1008252/61735157-a873e780-ad83-11e9-9b9e-1bad31c883b8.png)

Waere es eine Moeglichkeit zusaetzlich noch auf die "Erfolgreich teilgenommen" Labels zu gehen, ob ein Modul angerechnet wird in der Uebersicht oder nicht?

**Comment by eddex** [comment]
Die HSLU und ihre API überzeugen wirklich durch makellose Datenqualität :expressionless:

Werde mich darum kümmern. Module anhand des "Erfolgreich teilgenommen" als bestanden zu bewerten ist wohl die beste Möglichkeit.

**Comment by eddex** [comment]
foxed in v2.0.3
https://github.com/eddex/hslu-simple-mep-results/releases/tag/v2.0.3
