### ISSUE TITLE
TA.BA_VWL and I.BA_VWL conflict

### ISSUE THREAD

**Issue by CedHild** [eddex/hslu-simple-mep-results#71]
**Describe the bug**
VWL1 (TA.BA_VWL) is flagged as an "Erweiterungsmodul", even tho it should be a "Zusatzmodul". 

**Cause**
This probably happens because there is another module called I.BA_VWL that is an "Erweiterungsmodul". 
The module VWL1 is actually called TA.BA_VWL not TA.BA_VWL1 in mycampus.

**Comment by Lextum** [comment]
If anyone experiences this problem. Please try to fix it over the GUI, you should be able to remove and add modules as you please. If you want to fix this, feel free to open a pull request.
