### ISSUE TITLE
Module I.BA_CG missing

### ISSUE THREAD

**Issue by leylaciragan** [eddex/hslu-simple-mep-results#74]
**What do you study?**
- [x ] Informatik

**Which modules are not recognized by the add-on? And what type should they have?**
- I.BA_CG Computer Graphics, type "Majormodul"
- ...

**Screenshots**
[ Please provide screenshots of the Modules in the Module-List ]
![grafik](https://user-images.githubusercontent.com/47475811/90111523-0c7e9a80-dd4f-11ea-9663-252cfed38c0a.png)

**More info**
Is also of type: Erweiterungsmodul

**Comment by Lextum** [comment]
Should be fixed now with the new release.
