### ISSUE TITLE
Grade "0" (for not graded) is not shown - average grade calculation is off

### ISSUE THREAD

**Issue by leylaciragan** [eddex/hslu-simple-mep-results#75]
**Describe the bug**
Some modules I added manually (Modulerlassung) with grade "0", as they are not graded. 
-> Grade 0 does not show in the list (see screenshot below).
-> Calculation of average grade is probably wrong: ungraded credits should be subtracted from the calculation.

**Expected behavior**
- Grade 0 should show in the list
- Calculation of average grade should subtract credits with grade 0 

**Actual behavior**
- grade shows "n/a" like other modules
- no idea, how the calculation of average grade works here...

**Steps to Reproduce**

1. add a module manually, grade 0
2. watch the list

**Screenshots**
[ Add screenshots if possible. ]
![grafik](https://user-images.githubusercontent.com/47475811/90112104-daba0380-dd4f-11ea-86c2-351013a64b8e.png)

![grafik](https://user-images.githubusercontent.com/47475811/90112131-e3aad500-dd4f-11ea-96ea-9bd7805de246.png)

**Contributing (please choose one)**
- [ ] I'd like to help implementing this feature!
- [ ] I don't have the time to work on this.

**Comment by Lextum** [comment]
The status "n/a" for modules without grad or mark is correct. They also don't count against the average, how could they? 
Only modules with an F or a mark below 4 don't count to the total credits.

Did  miss something?

**Comment by leylaciragan** [comment]
Ok, thx, I thought, grade "0" would maybe show on the list instead of "n/a". 

About the average grade: yes, I saw that you only took the "passed" labelled courses. I did not see a calculation that **weighted** the grades by their number of credits, so I don't know, if the calculation is right. Normally, universities calculate it like this: 
weightedGradeOfModule = ECTSofPassedModule * grade
sumWeightedGrades = "sum up all weightedGradeOfPassedModule"
average = sumWeightedGrades/totalGradedECTS

But I don't know if HSLU does it this way.

If you just sum up the grades and sum up the credits separately (like in calculateStats()), divide by the totals, it does not show the weight, a **specific** module has on the average grade. E.g. a 6 ECTS module with 5.5 is "has more weight" than a 3 ECTS with 5.5., etc.

But - as I'm a total "beginner" in coding :-), it's very likely that I just missed this part in the code.... :-), and I don't know, what this line consists of exactly:
const average = Number(_Student.totalNumericMark / _Student.numberOfNumericMarks).toFixed(2);

Anyway, with my method, I get a slightly different result...? I can PM you my calc if you like. If I'm wrong, plz accept my apology for waisting your time :-)

**Comment by Lextum** [comment]
No, we do not weight the grade, this thought didn't cross our minds until now. I believe HSLU doesn't care about your average grade, as you just need 180 credits to pass. 
The average is really just stupid `sum(passed_grades) / count(passed_grades)`

**Comment by Lextum** [comment]
@leylaciragan could you look at my [commit](https://github.com/eddex/hslu-simple-mep-results/commit/dc92ee6f63860945b936520e6e92e19f70741399) ?
