### ISSUE TITLE
No ECTS points available anymore?

### ISSUE THREAD

**Issue by vigi86** [eddex/hslu-simple-mep-results#89]
**Describe the bug**
ECTS points are not listed anymore, thus the burn-down-chart isn't working

**Expected behavior**
ECTS string from original should be concatenated.

**Actual behavior**
No ECTS points visible.

**Steps to Reproduce**
Just open the page.

**Screenshots**
![image](https://user-images.githubusercontent.com/8401847/143028024-3b1fd931-8b02-42b2-a078-87ca5528a002.png)
![image](https://user-images.githubusercontent.com/8401847/143028194-9ebee041-3ea7-432e-8dd8-b7bb97ef3542.png)

**Contributing (please choose one)**
- [x] I'd like to help implementing this feature!
- [ ] I don't have the time to work on this.

Was there something wrong with #86 #87 or #88 ??

Edit: Probably #87...

**Comment by eddex** [comment]
Thanks for reporting! This is a know issue, as far as I remember @Lextum already implemented the fix for this but it's not deployed yet.

**Comment by vigi86** [comment]
Aight! 🤙🏻

**Comment by Lextum** [comment]
Yes, I added the fix in the merge request #87. @eddex and I just need to coordinate us, to release the fix.

**Comment by vigi86** [comment]
Thanks @Lextum !
I didn't realise it wasn't released yet. Then I was like "ah, stupid me" 😅

I was thinking about to take a look into IIM and implement the modules like I did for AI/ML last year, but the headers are totally different. But I'll give a try. 
And DI... we don't talk about DI and their google drive, right? 🥲

@eddex guess you can close the issue. I gonna run the extension from the local code and test it.

P.S. I'm in the walk-in space on the 2nd floor right now, if someone is down for a coffee ☕

**Comment by eddex** [comment]
We'll try to get the release out today. It's been pending for quite a while.

Problem is that I'm not studying anymore so I don't have access to the my-campus platform to do testing etc. @Lextum has taken over development and testing but I still own the Firefox developer account that is used to sign the extension. So we always have to coordinate. Will look into handing this over too to make things faster.

**Comment by Lextum** [comment]
We got the release out. Firefox should update automatically already, chrome needs maybe a day or two to pass the review.
